#!/bin/sh

export RUSTFLAGS=""
maturin develop --release --features python  # && python .\_t.py

export RUSTFLAGS='--cfg getrandom_backend="wasm_js"'
wasm-pack build --target bundler --no-typescript --release --features javascript
